app:
    resource: '@AppBundle/Controller/'
    type: annotation
books:
    path:      /books
    defaults:  { _controller: AppBundle:Books:list }
authors:
    path:      /authors
    defaults:  { _controller: AppBundle:Author:list }
genres:
    path:      /genres
    defaults:  { _controller: AppBundle:Genre:list }
profile:
    path:      /profile
    defaults:  { _controller: AppBundle:Profile:list}
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }
    